name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      GITHUB_PAGES: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build + Export
        env:
          NEXT_PUBLIC_SITE_URL: 'https://vexora-dev-ltda.github.io/VexoraDev'
        run: npm run build && npm run export

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
